export const FileExplorerData = {
  1: {
    id: 1,
    name: "File Explorer",
    type: "folder",
    parentId: null,
    children: [2, 3, 4],
  },
  2: {
    id: 2,
    name: "node_module",
    type: "folder",
    parentId: 1,
    children: [],
  },
  3: {
    id: 3,
    name: "public",
    type: "folder",
    parentId: 1,
    children: [5],
  },
  4: {
    id: 4,
    name: "src",
    type: "folder",
    parentId: 1,
    children: [6, 7, 8],
  },
  5: {
    id: 5,
    name: "vite.svg",
    type: "file",
    parentId: 3,
    children: [],
  },
  6: {
    id: 6,
    name: "assets",
    type: "folder",
    parentId: 4,
    children: [],
  },
  7: {
    id: 7,
    name: "App.js",
    type: "file",
    parentId: 3,
    children: [],
  },
  8: {
    id: 8,
    name: "App.css",
    type: "file",
    parentId: 3,
    children: [],
  },
  9: {
    id: 9,
    name: "react.svg",
    type: "file",
    parentId: 6,
    children: [],
  },
  10: {
    id: 10,
    name: "package.json",
    type: "file",
    parentId: 1,
    children: [],
  },
};
